In [1]:
import numpy

In [4]:
numpy.__version__  # 查看版本号

'1.15.1'

In [5]:
import numpy as np  # 取别名

In [6]:
np.__version__

'1.15.1'

## Python List 的特点

In [8]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L[5] = 100
L[5]

100

In [10]:
L[5] = "Machine Learning" # Python List 十分灵活，可以存储任意类型，所以带来的问题就是效率比较低，因为会检查每个元素的类型
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

## Python array 的特点

In [11]:
import array

In [12]:
arr = array.array('i', [i for i in range(10)]) # array只存放一种类型的数据
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [15]:
arr[5] = "Machine Learning"
arr

TypeError: an integer is required (got type str)

## numpy.array

In [16]:
nparr = np.array([i for i in range(10)]) 
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr[5] = "Machine Learning"  # 也只能存储一种类型
nparr

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [20]:
nparr.dtype  # 查看 nparr 数组中存储的数据类型

dtype('int32')

In [21]:
nparr[5] = 5.0  # 进行了一次隐式类型转换
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

## 其它创建 numpy.array 的方法

In [24]:
np.zeros(10) # 创建一个零数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10).dtype # 零数组默认数据类型为 float

dtype('float64')

In [28]:
np.zeros(10, dtype = int) # 创建10个整型元素的数组

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.zeros((3, 5))  # 创建一个三行五列的二维数组

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.ones(10) # 创建一个全1的一维数组

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [34]:
np.full(shape = (3, 5), fill_value = 10) # 参数的位置是可以改变的

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

### arange

In [35]:
[i for i in range(0, 20, 2)] #(0, 20, 2):起始点，终止点，步长(默认为1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
[i for i in range(0, 20, 0.2)] # range 中步长不能为浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
np.arange(0, 2, 0.2) # np.arange 中步长可以为浮点数

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [39]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [41]:
np.linspace(0, 20, 10) # 在0-20这个区间里等长的截出10个点（包括0和20）

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [42]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [43]:
np.random.randint(0, 10) # 生成[0,10)之间的一个随机数

5

In [44]:
np.random.randint(0, 10, 10) # 第三个参数：表示生成一个有10个元素的数组

array([3, 4, 9, 2, 5, 9, 5, 8, 8, 9])

In [45]:
np.random.randint(4, 8, size=10) # 便于观察，将大小进行标注

array([6, 5, 6, 6, 7, 7, 4, 5, 4, 6])

In [46]:
np.random.randint(4, 8, (3, 5)) # 生成一个矩阵

array([[7, 4, 5, 5, 5],
       [4, 4, 5, 4, 7],
       [6, 6, 4, 7, 6]])

In [48]:
np.random.seed(666) # 指定随机种子，使得每次随机值都一样

In [49]:
np.random.randint(4, 8, 10)

array([4, 6, 5, 6, 6, 6, 5, 6, 4, 5])

In [52]:
np.random.seed(666)

In [53]:
np.random.randint(4, 8, 10) # 与上次结果相同

array([4, 6, 5, 6, 6, 6, 5, 6, 4, 5])

In [55]:
np.random.random() # 默认生成0-1之间一个浮点数

0.41358769878652346

In [56]:
np.random.random(10)  # 生成一维数组

array([0.04881279, 0.09992856, 0.50806631, 0.20024754, 0.74415417,
       0.192892  , 0.70084475, 0.29322811, 0.77447945, 0.00510884])

In [57]:
np.random.random((3, 5)) # 生成二维数组

array([[0.11285765, 0.11095367, 0.24766823, 0.0232363 , 0.72732115],
       [0.34003494, 0.19750316, 0.90917959, 0.97834699, 0.53280254],
       [0.25913185, 0.58381262, 0.32569065, 0.88889931, 0.62640453]])

In [58]:
np.random.normal() # 生成一个符合正态分布的的浮点数，即均值为0，方差为1的随机浮点数

0.19459960304411825

In [59]:
np.random.normal(10, 100) # 指定均值为10，方差为100的浮点数

141.06377157249577

In [60]:
np.random.normal(0, 1, (3, 5)) # 参数三：大小

array([[ 1.5438436 , -0.52904802, -0.6564723 , -0.2015057 , -0.70061583],
       [ 0.68713795, -0.02607576, -0.82975832,  0.29655378, -0.3126795 ],
       [-0.61130127, -0.8217515 ,  0.8971227 ,  0.13607861, -0.2586548 ]])

In [64]:
np.random.normal? # 查看相关文档

SyntaxError: invalid syntax (<ipython-input-64-6c401378e679>, line 1)

In [65]:
np.random?

In [66]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap