In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [4]:
x.ndim # 查看数组是一维数组还是二维数组

1

In [5]:
X.ndim

2

In [6]:
x.shape # shape 返回的为一个元组

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
x.size # 返回数组元素个数

10

In [9]:
X.size 

15

### numpy.array 的数据访问 

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[0]

0

In [12]:
x[-1] # 可以为负数，-1为最后一个元素

9

In [13]:
X[0][0] # 不建议这么写

0

In [14]:
X[(1, 0)]

5

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[2, 2]

12

In [17]:
x[0:5] # 数组切片，不包含5

array([0, 1, 2, 3, 4])

In [18]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [19]:
x[5:]

array([5, 6, 7, 8, 9])

In [20]:
x[::2] # 第三个参数代表步长，也可以取负数，负数表示倒序访问

array([0, 2, 4, 6, 8])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
X[:2, :3] # 访问前两行，前三列的元素

array([[0, 1, 2],
       [5, 6, 7]])

In [23]:
X[:2][:3] # X[:2] 取X前两个元素，[:3] 再去上一步结果的前3个元素

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
X[::-1, ::-1] # 矩阵翻转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [25]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[0] # 取出第一行

array([0, 1, 2, 3, 4])

In [27]:
X[0, :]

array([0, 1, 2, 3, 4])

In [28]:
X[:, 0] # 取出第一列

array([ 0,  5, 10])

In [30]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [32]:
X # 为了效率，numpy会使用类似于引用的方式获取子矩阵

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [33]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
subX = X[:2, :3].copy() # 创建一个与原矩阵的无关的子矩阵
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX[0, 0] = 100
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [38]:
x.shape

(10,)

In [39]:
x.ndim

1

In [40]:
x.reshape(2, 5) # 将一维数组x变为一个2*5的二维数组 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
x # 并没有改变 x 本身

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
B = x.reshape(1, 10)
B # B 是一二维数组

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
B.ndim

2

In [48]:
x.reshape(10, -1) # 只要求10行，不关心列

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
x.reshape(-1, 10) # 不关心行，只要求10列

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
x.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [52]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [53]:
x

array([1, 2, 3])

In [54]:
y

array([3, 2, 1])

In [55]:
np.concatenate([x, y]) # 拼接,只能拼接维度相同的数组

array([1, 2, 3, 3, 2, 1])

In [56]:
z = np.array([666, 666, 666])

In [57]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [59]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [60]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate([A, A], axis=1) # 沿着列进行拼接

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
np.concatenate([A, z.reshape(1, -1)]) # 不改变原数组

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [64]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [65]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [67]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [69]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x1, x2, x3 = np.split(x, [3, 7])  # [3, 7] 指定两个分割点，3和7，如果这两个分割点合法，那么就将该数组切成3段

In [72]:
x1

array([0, 1, 2])

In [73]:
x2

array([3, 4, 5, 6])

In [74]:
x3

array([7, 8, 9])

In [76]:
x1, x2 = np.split(x, [5])

In [77]:
x1

array([0, 1, 2, 3, 4])

In [78]:
x2

array([5, 6, 7, 8, 9])

In [79]:
A = np.arange(16).reshape([4, 4])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
A1, A2 = np.split(A, [2]) # 默认在行上进行分割

In [81]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
A1, A2 = np.split(A, [2], axis = 1) # 按照列分割

In [84]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [85]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [86]:
upper, lower = np.vsplit(A, [2]) # 在垂直方向进行分割

In [87]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
left, right = np.hsplit(A, [2]) # 在水平方向分割

In [90]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [91]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [93]:
data = np.arange(16).reshape((4, 4)) # 假设只取前三列的值
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
X, y = np.hsplit(data, [-1]) # 把最后一列去掉
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [95]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [96]:
y[:, 0]

array([ 3,  7, 11, 15])