## Fancy Indexing（花式索引）

In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9] # 索引区间

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2] # 参数三：步长

array([3, 5, 7])

In [7]:
[x[3], x[5], x[8]] # 如果想要获取3，5，8

[3, 5, 8]

In [8]:
ind = [3, 5, 8] # 索引数组, Fancy Indexing
x[ind]

array([3, 5, 8])

In [10]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [11]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3]) # 只对(0,1),(1,2),(2,3)三个点感兴趣
X[row, col]

array([ 1,  6, 11])

In [16]:
X[0, col] # (0,1)(0,2)(0,3)

array([1, 2, 3])

In [17]:
X[:2, col] # 对前两行的第1，2，3列的元素感兴趣

array([[1, 2, 3],
       [5, 6, 7]])

In [19]:
col  = [True, False, True, True] # 可以使用布尔数组，对0，2，3列感兴趣
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较

In [20]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
x < 3 # 得到布尔数组

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [25]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [26]:
2 * x == 24 - 4 * x # 相当于解方程

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [27]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
np.sum(x <= 3) # 将True当作1，False当作0

4

In [31]:
np.count_nonzero(x <= 3) # 数组中非零元素(True)个数

4

In [32]:
np.any(x == 0) # 判断数组中是否有零元素

True

In [33]:
np.any(x < 0)

False

In [34]:
np.all(x >= 0)

True

In [35]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.sum(X % 2 == 0) # X中偶数个数

8

In [37]:
np.sum(X % 2 == 0, axis = 1) # 沿着列的方向，即每行中偶数个数

array([2, 2, 2, 2])

In [38]:
np.sum(X % 2 == 0, axis = 0)

array([4, 0, 4, 0])

In [39]:
np.all(X > 0, axis = 1)

array([False,  True,  True,  True])

In [40]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.sum((x > 3) & (x < 10)) #这里使用&，因为(x>3)和(x<10)得到的是两个数组，而不是两个条件，不能使用&&

6

In [42]:
np.sum((x%2 == 0) | (x > 10))

11

In [43]:
np.sum(~(x == 0))

15

In [44]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [45]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [47]:
X[X[:, -1] % 3 == 0, :] # 满足每一行中最后一列元素的值能够被3整除

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])