## 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.27521524, 0.48204917, 0.27885104, 0.87283181, 0.61937191,
       0.79997365, 0.04609091, 0.64377307, 0.98053622, 0.01421044,
       0.3670951 , 0.44526789, 0.27368467, 0.99939669, 0.23286193,
       0.35648229, 0.33046834, 0.29369082, 0.46695376, 0.07883544,
       0.57768435, 0.18390968, 0.90689547, 0.80136526, 0.16599528,
       0.59372125, 0.91851999, 0.31366514, 0.80490264, 0.90955009,
       0.57639995, 0.49954419, 0.96759305, 0.65871484, 0.34967204,
       0.89133043, 0.3909165 , 0.99359172, 0.87420955, 0.08115642,
       0.78696946, 0.76506367, 0.810998  , 0.9686602 , 0.30919452,
       0.5452359 , 0.34914744, 0.86270973, 0.6233292 , 0.66059709,
       0.78328122, 0.43118965, 0.7504942 , 0.00986189, 0.15592322,
       0.48511981, 0.53866133, 0.96233086, 0.61680792, 0.33853633,
       0.9287567 , 0.03122065, 0.77780761, 0.66134903, 0.5779288 ,
       0.60612523, 0.26302786, 0.425994  , 0.83541493, 0.08021769,
       0.88824022, 0.66571864, 0.30960627, 0.3016791 , 0.97411

In [3]:
sum(L) # sum可以计算list数组的和

54.31998319177786

In [4]:
np.sum(L) # 与上面的sum就是效率的区别

54.31998319177786

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array) # 效率更高

70.2 ms ± 302 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
488 µs ± 14.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
np.min(big_array)

1.8078496866191784e-07

In [9]:
np.max(big_array) # 也可以使用面向对象调用的方式

0.9999997797109165

In [10]:
big_array.min()

1.8078496866191784e-07

In [11]:
big_array.max()

0.9999997797109165

In [12]:
big_array.sum()

500608.69317063916

In [13]:
X = np.arange(16).reshape((4, -1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(X)

120

In [15]:
np.sum(X, axis = 0) # 沿着行进行计算，每一列的和

array([24, 28, 32, 36])

In [16]:
np.sum(X, axis = 1) # 每一行的和

array([ 6, 22, 38, 54])

In [17]:
np.prod(X) # X中所有元素的乘积

0

In [19]:
np.prod(X + 1)

2004189184

In [20]:
np.mean(X) # 平均值

7.5

In [21]:
np.median(X) # 中位数

7.5

In [22]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [23]:
np.median(v)

2.0

In [24]:
np.percentile(big_array, q=50) # big_array数组中有50%的数都是小于0.50113381

0.501133810269673

In [25]:
np.median(big_array) # 上面的值等同于中位数

0.501133810269673

In [26]:
np.percentile(big_array, q=100) # 等同于最大值

0.9999997797109165

In [27]:
np.max(big_array)

0.9999997797109165

In [30]:
for percent in [0, 25, 50, 75, 100]: # 通常对这个5个百分位点感兴趣 
    print(np.percentile(big_array, q = percent))

1.8078496866191784e-07
0.2506151770279257
0.501133810269673
0.7505211035251941
0.9999997797109165


In [32]:
np.var(big_array) #方差

0.08328552943414337

In [33]:
np.std(big_array) # 标准差

0.288592323934895

In [34]:
x = np.random.normal(0, 1, size = 1000000)

In [35]:
np.mean(x) # 均值，趋近于0

-0.001999304394196038

In [36]:
np.std(x) # 标准差，趋近于1

1.0008836611207377

## 索引

In [37]:
np.min(x)

-4.8284871533086955

In [38]:
np.argmin(x) # 寻找最小值的索引

225936

In [39]:
x[225936]

-4.8284871533086955

In [40]:
np.argmax(x) # 寻找最大值的索引

129087

In [41]:
x[129087]

4.851201421960059

In [42]:
np.max(x)

4.851201421960059

## 排序和使用索引

In [43]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
np.random.shuffle(x) # 将数组打乱
x

array([ 3,  7,  4, 11,  0, 12,  2, 13,  8,  9, 15,  6, 14,  1, 10,  5])

In [45]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
x # np.sort 生成一个新数组，没有改变数组本身

array([ 3,  7,  4, 11,  0, 12,  2, 13,  8,  9, 15,  6, 14,  1, 10,  5])

In [47]:
x.sort() # 原地排序
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
X = np.random.randint(10, size=(4, 4))
X

array([[7, 7, 8, 8],
       [1, 1, 9, 8],
       [8, 4, 8, 1],
       [1, 4, 2, 1]])

In [53]:
np.sort(X) # 将每一行进行升序排列

array([[7, 7, 8, 8],
       [1, 1, 8, 9],
       [1, 4, 8, 8],
       [1, 1, 2, 4]])

In [54]:
np.sort(X, axis = 1)# axis默认为1，沿者列的方向，即把每一行变为有序

array([[7, 7, 8, 8],
       [1, 1, 8, 9],
       [1, 4, 8, 8],
       [1, 1, 2, 4]])

In [55]:
np.sort(X, axis = 0) # 列有序

array([[1, 1, 2, 1],
       [1, 4, 8, 1],
       [7, 4, 8, 8],
       [8, 7, 9, 8]])

In [56]:
np.random.shuffle(x)
x

array([11,  7, 12,  3,  6,  8,  5, 15,  0,  9, 14,  2,  1,  4, 13, 10])

In [57]:
np.argsort(x) # 存放的是元素索引

array([ 8, 12, 11,  3, 13,  6,  4,  1,  5,  9, 15,  0,  2, 14, 10,  7],
      dtype=int64)

In [58]:
np.partition(x, 5) # 参数二：标定点；5之前的数字都比5小，5之后的数字都比5大

array([ 0,  1,  2,  4,  3,  5,  6,  7, 10,  9,  8, 11, 14, 12, 13, 15])

In [59]:
np.argpartition(x, 5)

array([ 8, 12, 11, 13,  3,  6,  4,  1, 15,  9,  5,  0, 10,  2, 14,  7],
      dtype=int64)

In [60]:
X

array([[7, 7, 8, 8],
       [1, 1, 9, 8],
       [8, 4, 8, 1],
       [1, 4, 2, 1]])

In [61]:
np.argsort(X, axis = 1) # 行有序

array([[0, 1, 2, 3],
       [0, 1, 3, 2],
       [3, 1, 0, 2],
       [0, 3, 2, 1]], dtype=int64)

In [62]:
np.argsort(X, axis = 0) # 列有序

array([[1, 1, 3, 2],
       [3, 2, 0, 3],
       [0, 3, 2, 0],
       [2, 0, 1, 1]], dtype=int64)

In [63]:
np.argpartition(X, 2, axis = 1)

array([[0, 1, 2, 3],
       [0, 1, 3, 2],
       [3, 1, 2, 0],
       [0, 3, 2, 1]], dtype=int64)

In [64]:
np.argpartition(X, 2, axis = 0)

array([[1, 1, 3, 2],
       [3, 2, 2, 3],
       [0, 3, 0, 0],
       [2, 0, 1, 1]], dtype=int64)