## scikit-learn 中的 kNN

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) #创建算法所对应的实例，n_neighbors就是传入的k

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ] # 原始数据特征
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1] # 原始数据的label，即所属类别，可以理解为0为良性肿瘤，1为恶性肿瘤

In [12]:
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)
x = np.array([8.093607318, 3.365731514])

In [13]:
kNN_classifier.fit(X_train, y_train) #拟合训练数据集，fit函数具有返回值

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [15]:
x_predict = x.reshape(1, -1)

In [16]:
kNN_classifier.predict(x_predict) # predict中希望传入一个矩阵

array([1])

In [17]:
y_predict = kNN_classifier.predict(x_predict)
y_predict

array([1])

In [18]:
y_predict[0]

1

### 重新整理我们的kNN的代码

In [39]:
%run D://python-code/KNN.py

In [40]:
knn_clf = kNNClassifier(k=6)

In [41]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [42]:
x_predict

array([[8.09360732, 3.36573151]])

In [43]:
y_predict = knn_clf.predict(x_predict)

In [44]:
y_predict

array([1])

In [45]:
y_predict[0]

1