## 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris() # 加载鸢尾花数据集

In [3]:
X = iris.data
y = iris.target

In [4]:
X # 鸢尾花的特征/属性

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y # label，即鸢尾花的类别

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### train_test_split

将原始数据集拆分成两部分，一部分作为训练数据集，另一部分作为测试数据集

#### 1. 将原始数据集乱序处理

因为我们看到 y 中的数据是排好序的

In [6]:
shuffle_indexes = np.random.permutation(len(X)) # 将索引乱序
shuffle_indexes # 0-149

array([ 16,  39, 115, 130,  50,  67,  28,  13,  64,  83,  81,  82, 105,
         6,  12,   1,  91,  53, 127,  65,   4,  57,  18,  97,  60,  25,
       148,  84,  99,  23, 104,  74,  98, 143,  29,  31,  22, 110,  70,
        24,  11, 111, 117,  69,  17,  93,  73, 125, 132, 101, 124, 120,
       129,   9,  77,  10,  32,  34, 103,  51,   8, 141,  86,  19,  45,
        44,  89,  58,  63,  54, 147,  20,   3,  68,  61,  30, 122, 109,
        40,  94,  90,  62,   7, 139,  88,  15,  26,  76,  55,  41,  36,
        48,   2, 128, 136,  56,  75, 144, 121,  79,  52,  80,  43, 131,
       137, 113,  49,  46,   0,  66, 140, 112, 114,  72,  35,  92, 145,
        42,  78, 102,  21,  38, 107, 146, 126,  85,  96,  47, 106, 118,
       138,  37, 135,  14, 142, 133,  59, 123, 116,  27, 108,  33,   5,
        87,  95, 134, 119, 149,  71, 100])

In [7]:
test_ratio = 0.2 # 测试数据集占原始数据的20%
test_size = int( len(X) * test_ratio ) # 测试数据集的个数
test_size

30

In [8]:
test_indexes = shuffle_indexes[:test_size] # 测试数据集

In [12]:
train_indexes = shuffle_indexes[test_size:] # 训练数据集

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [15]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 使用我们的算法

In [17]:
%run D:\\python-code\train_test_split.py

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [20]:
%run D:\\python-code\KNN.py # 上一篇博客中自己封装的kNN算法

In [21]:
my_knn = kNNClassifier(k=3)

In [22]:
my_knn.fit(X_train, y_train)

KNN(k=3)

In [23]:
y_predict = my_knn.predict(X_test)
y_predict

array([0, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 2,
       1, 0, 1, 0, 1, 1, 1, 0])

In [24]:
y_test # 与y_predict进行比对

array([0, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 2,
       1, 0, 1, 0, 1, 1, 1, 0])

In [25]:
sum(y_predict == y_test) # 30个元素其中有29个相等

29

In [26]:
sum(y_predict == y_test) / len(y_test) #y 预测正确率

0.9666666666666667

#### sklearn中的train_test_split

In [27]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [29]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
kNN_classifier = KNeighborsClassifier(n_neighbors=3)

In [33]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [34]:
y_predict = kNN_classifier.predict(X_test)

In [35]:
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [36]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [37]:
sum(y_predict == y_test)

30

In [38]:
sum(y_predict == y_test) / len(y_test)

1.0