## Scikit-learn中的Scaler

In [29]:
import numpy as np
from sklearn import datasets

In [30]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [31]:
X[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [32]:
# train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

### 1. 首先对 X_train 进行归一化处理

scikit-learn 中的 StandardScaler

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
standardScaler = StandardScaler()

In [35]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
standardScaler.mean_ # 均值，4列的均值

array([5.83416667, 3.0825    , 3.70916667, 1.16916667])

In [37]:
standardScaler.scale_ # 标准差

array([0.81019502, 0.44076874, 1.76295187, 0.75429833])

In [38]:
standardScaler.transform(X_train) #将X_train进行归一化处理，这种方式下X_train本身没有改变

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [39]:
X_train = standardScaler.transform(X_train)

In [40]:
X_train

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [41]:
X_test_standard = standardScaler.transform(X_test) # 将测试数据进行归一化
X_test_standard

array([[-0.28902506, -0.18717298,  0.44858475,  0.43859746],
       [-0.04217092, -0.64092567,  0.78892303,  1.63175932],
       [-1.0295875 , -1.77530738, -0.2320918 , -0.22427024],
       [-0.04217092, -0.86780201,  0.78892303,  0.96889162],
       [-1.52329579,  0.03970336, -1.25310662, -1.28485856],
       [-0.41245214, -1.3215547 ,  0.16496953,  0.17345038],
       [-0.16559799, -0.64092567,  0.44858475,  0.17345038],
       [ 0.82181859, -0.18717298,  0.84564608,  1.10146516],
       [ 0.57496445, -1.77530738,  0.39186171,  0.17345038],
       [-0.41245214, -1.09467835,  0.39186171,  0.04087684],
       [ 1.06867274,  0.03970336,  0.39186171,  0.30602392],
       [-1.64672287, -1.77530738, -1.36655271, -1.15228502],
       [-1.27644165,  0.03970336, -1.19638358, -1.28485856],
       [-0.53587921,  0.72033239, -1.25310662, -1.01971148],
       [ 1.68580811,  1.17408507,  1.35615349,  1.76433286],
       [-0.04217092, -0.86780201,  0.22169257, -0.22427024],
       [-1.52329579,  1.

### 2. 将归一化后的数据进行 kNN 分类

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.score(X_test_standard, y_test) #传入的测试数据集必须是归一化后的测试数据集。

1.0

In [44]:
knn_clf.score(X_test, y_test) # 若没有进行归一化处理

0.3333333333333333

### 3. 封装自己的 StandardScaler

In [45]:
%run D:\\python-code\preprocessing.py

In [46]:
myScaler = StandardScaler()

In [47]:
myScaler.fit(X_train)

In [48]:
X_train = myScaler.transform(X_train)
X_train

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [51]:
X_test_scaler = myScaler.transform(X_test)
X_test_scaler

array([[5.6, 3. , 4.5, 1.5],
       [5.8, 2.8, 5.1, 2.4],
       [5. , 2.3, 3.3, 1. ],
       [5.8, 2.7, 5.1, 1.9],
       [4.6, 3.1, 1.5, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [6.5, 3. , 5.2, 2. ],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3.1, 4.4, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.7, 4.1, 1. ],
       [4.6, 3.6, 1. , 0.2],
       [7.2, 3.2, 6. , 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.3, 3.3, 4.7, 1.6],
       [5. , 3.4, 1.5, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [5. , 3.3, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.9, 3. , 4.2, 1.5],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [6.3, 3.3, 6. , 2.5],
       [7.7, 3. , 6.1, 2.3]])

In [50]:
knn_clf.fit(X_train, y_train)
knn_clf.score(X_test_scaler, y_test)

0.3333333333333333